name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 14 * * 3" # Run Wednesdays at 2pm EST

jobs:
  php-tests:
    strategy:
      matrix:
        dependency-version: [stable, lowest]
        os: [ubuntu, windows]
        laravel: [12.*, 13.*]
        php: [8.3, 8.4, 8.5]
        livewire: [3.*, 4.*]

    runs-on: "${{ matrix.os }}-latest"
    timeout-minutes: 10

    name: "${{ matrix.os }}: ${{ matrix.php }} / ${{ matrix.laravel }} / ${{ matrix.livewire }} (${{ matrix.dependency-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv, fileinfo
          tools: composer:v2

      - name: Register composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: ${{ steps.composer-cache.outputs.dir != '' }}
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require --no-interaction --prefer-dist --update-with-all-dependencies --prefer-${{ matrix.dependency-version }} "illuminate/support:${{ matrix.laravel }}" "livewire/livewire:${{ matrix.livewire }}"

      - name: Execute tests
        run: vendor/bin/phpunit
